"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const score_controller_1 = require("../controllers/score.controller");
const auth_1 = require("../middleware/auth");
const requireActiveSubscription_1 = require("../middleware/requireActiveSubscription");
const router = (0, express_1.Router)();
router.use(auth_1.requireAuth);
router.use(requireActiveSubscription_1.requireActiveSubscription);
router.get('/', score_controller_1.getScores);
router.post('/', score_controller_1.createScore);
router.put('/:id', score_controller_1.updateScore);
router.delete('/:id', score_controller_1.deleteScore);
exports.default = router;
